--1.	Which magazine is the highest in stock?
SELECT MAG_ID,TITLE,QUANTITY FROM INVENTORY_TABLE_SP
WHERE QUANTITY IN (select max(QUANTITY) AS HIGHEST_QUANTITY
FROM INVENTORY_TABLE_SP);

--2.	Which all magazines are near out of stock? ORDER BY ASC
SELECT MAG_ID AS MAGZINEid ,TITLE AS MAGZINEname,QUANTITY AS QUANTITY_LESS_THAN_30 FROM INVENTORY_TABLE_SP 
WHERE QUANTITY IN ((SELECT QUANTITY FROM INVENTORY_TABLE_SP
WHERE QUANTITY<30));

--3. 	Which all magazines in the inventory are marked as special issue?
SELECT TITLE AS SPECIAL_ISSUES_OF_MAGZINE FROM INVENTORY_TABLE_SP
WHERE MAG_ID IN (
(SELECT MAG_ID FROM INVENTORY_TABLE_SP
WHERE SPECIAL_ISSUE='YES')
);

--4. 4.	Which magazine has the highest number of hit?
select inv.TITLE,inv.mag_id,count(od.mag_id)as HighestHits_of_MAGS from ORDER_TABLE_SP od
inner join INVENTORY_TABLE_SP inv
on od.MAG_ID=inv.MAG_ID
group by inv.TITLE,inv.MAG_ID,od.mag_id;

--5.	Which customer has made the highest value of purchase till day?
select CST.CUST_FIRST_NAME,CST.CUST_LAST_NAME, bt.cust_id,bt.TOTAL_BILL_AMT from billing_table_sp bt INNER JOIN CUSTOMER_TABLE_SP CST
ON bt.CUST_ID=CST.CUST_ID
where bt.TOTAL_BILL_AMT=(select MAX(bt.total_bill_amt) from billing_table_sp bt)
;

--6.	Which customer has purchased highest quantity of products at a time?
SELECT CST.CUST_FIRST_NAME,CST.CUST_LAST_NAME,OD.QUANTITY FROM ORDER_TABLE_SP OD INNER JOIN CUSTOMER_TABLE_SP CST
ON OD.CUST_ID=CST.CUST_ID WHERE CST.CUST_ID=(
SELECT OD.CUST_ID FROM ORDER_TABLE_SP OD 
WHERE OD.QUANTITY IN((SELECT MAX(OD.QUANTITY) AS MAX_QUANTITY FROM ORDER_TABLE_SP OD)));

--7.	What is the average price of all the products sold on a particular date RANGE?
SELECT AVG(PRICE_COL)AS AVG_PRC_OF_PROD FROM (
SELECT INV.PRICE AS PRICE_COL FROM INVENTORY_TABLE_SP INV WHERE INV.MAG_ID IN

(SELECT OD.MAG_ID FROM ORDER_TABLE_SP OD INNER JOIN BILLING_TABLE_SP BT
ON OD.ORDER_ID=BT.ORDER_ID 
WHERE BT.ORDER_ID IN(
(SELECT BT.ORDER_ID FROM BILLING_TABLE_SP BT
WHERE BT.DATE_OF_PURCHASE BETWEEN '01-JAN-14' AND '30-SEP-14'))) )
;

--8.	Which is the destination the shop has shipped to the most?
SELECT SL.LOCATION FROM SHOP_LOCATION_SP SL  WHERE SL.SHOP_LOC_ID =
(
SELECT SHOP_LOC_ID FROM 
(SELECT ST.SHOP_LOC_ID ,COUNT(ST.SHOP_LOC_ID) AS lOC_SHIP_TIMES FROM SHIPPING_TABLE_SP ST
GROUP BY ST.SHOP_LOC_ID)
WHERE LOC_SHIP_TIMES IN 
(SELECT MAX(LOC_SHIP_TIMES) FROM
(
SELECT ST.SHOP_LOC_ID ,COUNT(ST.SHOP_LOC_ID) AS LOC_SHIP_TIMES FROM SHIPPING_TABLE_SP ST
GROUP BY ST.SHOP_LOC_ID
))
);

--9.	What is the highest discount given to any customer?
SELECT CST.CUST_EMAIL AS CUST_WITH_MAX_DISC ,CST.CUST_FIRST_NAME,CST.CUST_LAST_NAME,BT.CUST_ID, BT.DISCOUNT 
FROM BILLING_TABLE_SP BT INNER JOIN CUSTOMER_TABLE_SP CST
ON BT.CUST_ID=CST.CUST_ID
WHERE BT.DISCOUNT=(
SELECT MAX(BT.DISCOUNT)AS MAX_DIS_RECV FROM BILLING_TABLE_SP BT);

--10.	Which supplier has exported the most to the magazine store’s inventory in the month of JAN FEB and March?
SELECT  SP.SUPPLIER_NAME ,INV.SUPPLIER_ID ,INV.TITLE FROM SUPPLIERS_TABLE_SP SP INNER JOIN INVENTORY_TABLE_SP INV
ON SP.SUPPLIER_ID=INV.SUPPLIER_ID
WHERE INV.SUPPLIER_ID IN(

SELECT INV.SUPPLIER_ID FROM INVENTORY_TABLE_SP INV
WHERE MONTH BETWEEN '01-JAN-17'AND '31-MAR-17'
);

--11. GROUP BY CLAUSE WITH HAVING 
SELECT BT.ORDER_ID ,SUM(BT.TOTAL_BILL_AMT)AS SUM_FOR_ORDER_ID
FROM BILLING_TABLE_SP  BT INNER JOIN CUSTOMER_TABLE_SP CST
ON BT.CUST_ID=CST.CUST_ID
GROUP BY ORDER_ID
HAVING SUM(TOTAL_BILL_AMT) >100;





