-- 1. SUPPLIERS_TABLE_SP DONE
CREATE TABLE SUPPLIERS_TABLE_SP
(
SUPPLIER_ID         NUMBER(30) NOT NULL PRIMARY KEY,
SUPPLIER_NAME       VARCHAR2(30)NOT NULL,
LOCATION            VARCHAR2(30)NOT NULL               

);

-- 2. INVENTORY_TABLE_SP  DONE
CREATE TABLE INVENTORY_TABLE_SP
(
MAG_ID              NUMBER(30) NOT NULL PRIMARY KEY,
TITLE               VARCHAR2(30)NOT NULL,
QUANTITY            NUMBER(30)NOT NULL,
PRICE               NUMBER(30)NOT NULL,
SUPPLIER_ID         NUMBER(30)NOT NULL, --FOREIGN KEY FROM SUPPLIERS_TABLE_SP
MONTH               DATE NOT NULL,
SPECIAL_ISSUE       VARCHAR2(5) CHECK(SPECIAL_ISSUE='YES' OR SPECIAL_ISSUE='NO'),

CONSTRAINT SUPPLIER_ID_FK_SP FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS_TABLE_SP(SUPPLIER_ID)

);

-- 3. CUSTOMER_TABLE_SP  DONE
CREATE TABLE CUSTOMER_TABLE_SP
(
CUST_ID             NUMBER(30) NOT NULL PRIMARY KEY,
MEMBERSHIP_TYPE     VARCHAR2(30)NOT NULL,
CUST_EMAIL          VARCHAR2(30)NOT NULL,
CUST_NUM            NUMBER(10) NOT NULL,
ADDRESS             VARCHAR2(225) NOT NULL,
CUST_DOJ            DATE NOT NULL,
DOB                 DATE NOT NULL,
ANNIVERSARY_DATE    DATE NOT NULL

);
-- 4. COMPANION_TABLE_SP DONE
CREATE TABLE COMPANION_TABLE_SP
(
COMP_ID             NUMBER(30) NOT NULL PRIMARY KEY,
COMP_PROD_NAME      VARCHAR2(30)NOT NULL,
DESCRIPTION         VARCHAR2(225)NOT NULL               

);

-- 5. SHOP_LOCATION_SP DONE
CREATE TABLE SHOP_LOCATION_SP
(
SHOP_LOC_ID         NUMBER(30) NOT NULL PRIMARY KEY,
LOCATION            VARCHAR2(30)NOT NULL  
);

--5.5. ORDER_TABLE_SP DONE
--DROP TABLE ORDER_TABLE_SP
CREATE TABLE ORDER_TABLE_SP
(
--ID                  NUMBER(30) NOT NULL PRIMARY KEY,
ORDER_ID            NUMBER(30)NOT NULL   ,
SHOP_LOC_ID         NUMBER(30)NOT NULL, -- FOREGIN KEY FROM SHOP_LOCATION_SP TABLE
MAG_ID              NUMBER(30) NOT NULL,-- FOREIGN KEY FROM INENTORY_TABLE_SP
QUANTITY            NUMBER NOT NULL,
CUST_ID             NUMBER(30) NOT NULL   ,--FOREIGN KEY FROM CUSTOMER_TABLE_SP
COMP_ID             NUMBER(30) NOT NULL,--FOREIGN KEY FROM COMPANION_TABLE_SP
CONSTRAINT PRIMARY_KEY_SP PRIMARY KEY(ORDER_ID,CUST_ID),
CONSTRAINT SHOP_LOC_ID_SP_FK FOREIGN KEY(SHOP_LOC_ID) REFERENCES SHOP_LOCATION_SP(SHOP_LOC_ID),
CONSTRAINT MAG_ID_SP_FK FOREIGN KEY(MAG_ID) REFERENCES INVENTORY_TABLE_SP(MAG_ID),
CONSTRAINT CUST_ID_FK_SP FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER_TABLE_SP(CUST_ID),
CONSTRAINT COMP_ID_FK_SP FOREIGN KEY(COMP_ID)REFERENCES COMPANION_TABLE_SP(COMP_ID)

);

-- 6. BILLING_TABLE_SP DONE
CREATE TABLE BILLING_TABLE_SP
(
BILL_NO             NUMBER(30) NOT NULL PRIMARY KEY,
CUST_ID             NUMBER(30) NOT NULL,
ORDER_ID            NUMBER(30) NOT NULL ,--FOREIGN KEY FROM ORDER_TABLE_SP
DATE_OF_PURCHASE    DATE NOT NULL,
TOTAL_BILL_AMT      NUMBER NOT NULL,
DISCOUNT            NUMBER(20) NOT NULL,
CONSTRAINT ORDER_ID_FK_SP FOREIGN KEY(ORDER_ID,CUST_ID)REFERENCES ORDER_TABLE_SP(ORDER_ID,CUST_ID)
);

--7. SHIPPING_TABLE_SP
CREATE TABLE SHIPPING_TABLE_SP
(
SHIPPING_ID         NUMBER(30) NOT NULL PRIMARY KEY,
BILL_NO             NUMBER(30) NOT NULL,--FOREIGN KEY FROM BILLING TABLE
SHOP_LOC_ID         NUMBER(30) NOT NULL ,--FOREIGN KEY FROM SHOPLOCATION TABLE

CONSTRAINT BILL_NO_FK_SP FOREIGN KEY(BILL_NO)REFERENCES BILLING_TABLE_SP(BILL_NO),
CONSTRAINT SHOP_LOC_ID_FK_SP FOREIGN KEY(SHOP_LOC_ID) REFERENCES SHOP_LOCATION_SP(SHOP_LOC_ID)
);



